spring:
  profiles:
    active: local

---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  session:
    store-type: jdbc
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false

    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/21days
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace

---

spring:
  config:
    activate:
      on-profile: mysql
      jdbc-url: jdbc:mysql://localhost:3306/21days?useUnicode=true&characterEncoding=utf8
      username: yooyeon
        password: yooyeon1234@
        driver-class-name: com.mysql.cj.jdbc.Driver
